[versions]
commonsVfsVersion = "2.10.0"
dotenvVersion = "2.2.0"
hikariCpVersion = "5.1.0"
jacksonVersion = "2.18.2"
javalinVersion = "6.7.0"
jdbiVersion = "3.47.0"
jeeAnnotationApiVersion = "3.0.0"
kotlinVersion = "2.0.20"
log4jCoreVersion = "2.24.3"
mysqlConnectorVersion = "9.3.0"
slf4jApiVersion = "2.0.16"
springVaultVersion = "4.0.0"
springRabbitMqVersion = "3.2.4"
springVersion = "6.2.12"
yauaaVersion = "7.30.0"

[libraries]
commonsVfs = { module = "org.apache.commons:commons-vfs2", version.ref = "commonsVfsVersion" }
dotEnv = { module = "io.github.cdimascio:dotenv-java", version.ref = "dotenvVersion" }
hikariCp = { module = "com.zaxxer:HikariCP", version.ref = "hikariCpVersion" }
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonVersion" }
jacksonDataformatYaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jacksonVersion" }
jacksonJsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jacksonVersion" }
jacksonKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonVersion" }
javalin = { module = "io.javalin:javalin", version.ref = "javalinVersion" }
jdbi = { module = "org.jdbi:jdbi3-core", version.ref = "jdbiVersion" }
jdbiKotlin = { module = "org.jdbi:jdbi3-kotlin", version.ref = "jdbiVersion" }
jeeAnnotationApi = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jeeAnnotationApiVersion" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinVersion" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVersion" }
log4jCore = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4jCoreVersion" }
mysqlConnector = { module = "com.mysql:mysql-connector-j", version.ref = "mysqlConnectorVersion" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApiVersion" }
springContext = { module = "org.springframework:spring-context", version.ref = "springVersion" }
springRabbitMq = { module = "org.springframework.amqp:spring-rabbit", version.ref = "springRabbitMqVersion" }
springVault = { module = "org.springframework.vault:spring-vault-core", version.ref = "springVaultVersion" }
yauaa = { module = "nl.basjes.parse.useragent:yauaa", version.ref = "yauaaVersion" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
